### ISSUE TITLE
Issues with the notebooks 

### ISSUE THREAD

**Issue by sauter-roland** [SBRG/Recon3D#1]
Hi!

Unfortunately I'm having some issues witht the notebooks provided for the GEM-PRO models.
First they crash at the import statement as there is " No module named 'ssbio.core.io' ". Changing the import statement to `from ssbio.io import load_json` solves this.
Both notebooks then throw an error when reading _Recon3D_GP/model/Recon3D_GP.json.gz_ as it is not recognized as a gzipped format. Gunzip concurs.

Thanks!
Roland

**Comment by nmih** [comment]
Hi Roland, thanks for bringing this to our attention. A couple things have changed since we first released both ssbio and Recon3D, but I believe it's mainly some naming issues. I will check it out and upload an updated model asap.

**Comment by nmih** [comment]
I've updated the model files and notebooks, please let me know if you have any issues with them! 

Thanks, 
Nathan

**Comment by sauter-roland** [comment]
Hi Nathan,
Neither the JSON, nor the pickle can be loaded. Both files are extremely small with 133/134 bytes and only contain a version link, checksum and size.

Best,
Roland

**Comment by nmih** [comment]
Hi Roland, the reason for that is because they are under the "large file storage" (LFS) system of git. If you clone the whole repository it should grab the correct file on your local disk. I have changed the json.gz file to not be under LFS so that can be downloaded from the website now, since it is small enough to not need that.

**Comment by sauter-roland** [comment]
Hi Nathan.
It works fine now, thanks for the support! For some reason the LFS didn't do that even though I cloned.
